wontfix:
- .gitignore
- LICENSE

"@edgelabs/app":
- apps/app/*
- apps/app/**/*

"@edgelabs/groot":
- apps/groot/*
- apps/groot/**/*

"@edgelabs/cli":
- packages/cli/*
- packages/cli/**/*

"@edgelabs/types":
- packages/types/*
- packages/types/**/*
