version: "3.7"
services:
  # Edge API
  api:
    build:
      context: .github
      dockerfile: pnpm.dockerfile
    command: pnpm dev
    working_dir: /app/services/api
    volumes:
      - ./:/app
    ports:
      - 1234:1234
    depends_on:
      - db
      - minio
    # DB_IP variable to 1
    environment:
      - ENVIRONMENT=development
      - DB_IP=scylla:9042
      - DB_DATACENTER=datacenter1
      - INSTANCE_ID=1
      - REDIS_IP=db
      - SIGNALFS_HOST=minio

  # Frontend (Developmment Mode)

  app:
    build:
      context: .github
      dockerfile: pnpm.dockerfile
    command: pnpm dev --host
    working_dir: /app/web/app
    volumes:
      - ./:/app
    ports:
      - 5173:5173
    depends_on:
      - db
      - minio
    # DB_IP variable to 1
    environment:
      - ENVIRONMENT=development
      - VITE_API_URL=http://localhost:1234

  # Redis
  db:
    image: redis:alpine
    ports:
      - "6379:6379"
  # Object Storage
  minio:
    image: minio/minio
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=minio
      - MINIO_ROOT_PASSWORD=wachtwoord
  # ScyllaDB
  scylla:
    image: scylladb/scylla
    command:  ["--developer-mode", "1", "--smp", "1"]
    ports:
      - "9042:9042"
