name: Deploy App to Staging

on: workflow_dispatch
# on:
#   push:
#     branches:
#       - master
#     paths:
#       - "apps/app/**"
#       - ".github/workflows/staging-app.yml"

jobs:
  zip-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - uses: pnpm/action-setup@v2.0.1
        name: Install pnpm
        id: pnpm-install
        with:
          version: 7
          run_install: false

      - name: Get pnpm store directory
        id: pnpm-cache
        run: |
          echo "::set-output name=pnpm_cache_dir::$(pnpm store path)"
      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.pnpm_cache_dir }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-
      - name: Install dependencies
        run: pnpm install
      - name: Build
        run: pnpm turbo run build --filter @edgelabs/app
        env:
          VITE_API_URL: "https://api.edgeserver.dev"
      - name: Edgeserver Upload
        uses: lvkdotsh/edgeserver-action@master
        with:
          app_id: "61535119206256640"
          server: https://api.edgeserver.io
          token: ${{ secrets.SIGNAL_TOKEN }}
          directory: apps/app/dist
